package errmsg

const (
	SUCCESS = 200
	ERROR   = 500

	// 用户模块的错误
	ERROR_USERNAME_USED    = 1001
	ERROR_PASSWORD_WRONG   = 1002
	ERROR_USER_NOT_EXIST   = 1003
	ERROR_TOKEN_EXIST      = 1004
	ERROR_TOKEN_RUNTIME    = 1005
	ERROR_TOKEN_WRONG      = 1006
	ERROR_TOKEN_TYPE_WRONG = 1007
	ERROR_USER_NO_RIGHT    = 1008

	// 文章模块的错误
	ERROR_ART_NOT_EXIST = 2001

	// 分类模块的错误
	ERROR_CATENAME_USED  = 3001
	ERROR_CATE_NOT_EXIST = 3002

	// 附件模块的错误
	ERROR_ATTACHMENT_NOT_EXIST    = 4001
	ERROR_ATTACHMENT_UPLOAD_FAIL  = 4002
	ERROR_ATTACHMENT_DELETE_FAIL  = 4003
	ERROR_ATTACHMENT_INVALID      = 4004
	ERROR_ATTACHMENT_DIR_CREATE   = 4005
	ERROR_ATTACHMENT_FILE_SAVE    = 4006
	ERROR_ATTACHMENT_BATCH_FAIL   = 4007
	ERROR_ATTACHMENT_INVALID_ART  = 4008
	ERROR_ATTACHMENT_FILE_MISSING = 4009
)

var codeMsg = map[int]string{
	SUCCESS:                "OK",
	ERROR:                  "FAIL",
	ERROR_USERNAME_USED:    "用户名已存在！",
	ERROR_PASSWORD_WRONG:   "密码错误",
	ERROR_USER_NOT_EXIST:   "用户不存在",
	ERROR_TOKEN_EXIST:      "TOKEN不存在,请重新登陆",
	ERROR_TOKEN_RUNTIME:    "TOKEN已过期,请重新登陆",
	ERROR_TOKEN_WRONG:      "TOKEN不正确,请重新登陆",
	ERROR_TOKEN_TYPE_WRONG: "TOKEN格式错误,请重新登陆",
	ERROR_USER_NO_RIGHT:    "该用户无权限",

	ERROR_ART_NOT_EXIST: "文章不存在",

	ERROR_CATENAME_USED:  "该分类已存在",
	ERROR_CATE_NOT_EXIST: "该分类不存在",

	// 附件错误信息
	ERROR_ATTACHMENT_NOT_EXIST:    "附件不存在",
	ERROR_ATTACHMENT_UPLOAD_FAIL:  "附件上传失败",
	ERROR_ATTACHMENT_DELETE_FAIL:  "附件删除失败",
	ERROR_ATTACHMENT_INVALID:      "无效的附件",
	ERROR_ATTACHMENT_DIR_CREATE:   "创建附件目录失败",
	ERROR_ATTACHMENT_FILE_SAVE:    "保存附件文件失败",
	ERROR_ATTACHMENT_BATCH_FAIL:   "批量上传附件失败",
	ERROR_ATTACHMENT_INVALID_ART:  "无效的文章ID",
	ERROR_ATTACHMENT_FILE_MISSING: "附件文件不存在",
}

func GetErrMsg(code int) string {
	return codeMsg[code]
}
